version: '3.8'

services:
  web:
    image: your_server_image
    build: .
    environment:
      DB_CLIENT: mysql
      DB_USER: exampleuser
      DB_PASS: examplepass
      DB_NAME: exampledb
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
