apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: web
    app: wab
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
        - image: your_server_image
          name: web
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
